name: jaguar_query_mysql1
description: mysql1 adapter for jaguar_query
version: 2.2.7
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>

homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  jaguar_query: ^2.2.6
  mysql1:
    git: git://github.com/Hexer10/mysql1_dart.git
  path: ^1.6.2

dev_dependencies:
  test: ^1.3.0
